// Auto-generated by fetch_soros_fred.py · DO NOT EDIT MANUALLY
// Last update: 2026-08-17 00:18 UTC
const FRED_DATA = {
  "updated_at": "2026-08-17 00:18 UTC",
  "flipped_count": 1,
  "flipped_total": 7,
  "signals": {
    "S1": {
      "current": "2.39%",
      "status": "红色",
      "pill": "pill-red",
      "delta_30d": "+0.14% · 30D",
      "date": "2026-08-13"
    },
    "S2": {
      "current": "271bp",
      "status": "正常",
      "pill": "pill-green",
      "delta_30d": "-4bp · 30D",
      "date": "2026-08-13"
    },
    "AUX_BEI": {
      "current": "2.27%",
      "status": "正常",
      "pill": "pill-green",
      "delta_30d": "+0.04% · 30D",
      "date": "2026-08-14"
    },
    "AUX_DXY": {
      "current": "119.06",
      "status": "正常",
      "pill": "pill-green",
      "delta_30d": "-1.99 · 30D",
      "date": "2026-08-07"
    },
    "AUX_DGS10": {
      "current": "4.63%",
      "status": "正常",
      "pill": "pill-green",
      "delta_30d": "+0.15% · 30D",
      "date": "2026-08-13"
    },
    "AUX_VIX": {
      "current": "14.63",
      "status": "正常",
      "pill": "pill-green",
      "delta_30d": "-1.52 · 30D",
      "date": "2026-08-13"
    }
  },
  "weekly": {
    "gpu_prices": {
      "H200": {
        "min_hr": "$3.23/hr",
        "median_hr": "$3.94/hr",
        "max_hr": "$3.94/hr",
        "offers": 2,
        "date": "2026-08-17"
      },
      "B200": {
        "min_hr": "$5.31/hr",
        "median_hr": "$5.31/hr",
        "max_hr": "$5.31/hr",
        "offers": 2,
        "date": "2026-08-17"
      }
    },
    "form4": {
      "NVDA": {
        "count_30d": 2,
        "latest_date": "2026-08-12",
        "status": "正常",
        "pill": "pill-green"
      },
      "MSFT": {
        "count_30d": 2,
        "latest_date": "2026-08-06",
        "status": "正常",
        "pill": "pill-green"
      },
      "GOOGL": {
        "count_30d": 14,
        "latest_date": "2026-08-11",
        "status": "正常",
        "pill": "pill-green"
      },
      "META": {
        "count_30d": 7,
        "latest_date": "2026-08-12",
        "status": "正常",
        "pill": "pill-green"
      },
      "ORCL": {
        "count_30d": 1,
        "latest_date": "2026-07-28",
        "status": "正常",
        "pill": "pill-green"
      }
    }
  },
  "events": {
    "tips_daily": {
      "change_bp": -3.0,
      "triggered": false,
      "date": "2026-08-13",
      "level": "2.39%"
    },
    "capex": {
      "triggered": false,
      "status": "监控中 · 近7日20条",
      "pill": "pill-green",
      "headline": "Sundar Pichai Raised Alphabet's Capex Guidance to $205 Billion the Same Quarter Google Cloud's Backlog Hit $514 Billion. Here's Which Number",
      "date": "2026-08-16",
      "match": "",
      "count_7d": 20
    },
    "neocloud": {
      "triggered": true,
      "status": "触发复核",
      "pill": "pill-red",
      "headline": "Nebius: Avoid Chasing, Even If You Missed The Ride (Rating Downgrade) - Seeking Alpha",
      "date": "2026-08-16",
      "match": "downgrade",
      "count_7d": 28
    },
    "bond": {
      "triggered": false,
      "status": "监控中 · 近7日4条",
      "pill": "pill-green",
      "headline": "Soaring AI hyperscaler default hedges aren't what they seem - Reuters",
      "date": "2026-08-12",
      "match": "",
      "count_7d": 4
    },
    "abs": {
      "triggered": false,
      "status": "监控中 · 近7日1条",
      "pill": "pill-green",
      "headline": "North America Data Center Report Midyear 2026 - JLL",
      "date": "2026-08-11",
      "match": "",
      "count_7d": 1
    },
    "policy": {
      "triggered": false,
      "status": "监控中 · 近7日4条",
      "pill": "pill-green",
      "headline": "Moolenaar urges stronger enforcement of chip export controls - riponadvance.com",
      "date": "2026-08-12",
      "match": "",
      "count_7d": 4
    },
    "leverage": {
      "triggered": true,
      "status": "触发复核",
      "pill": "pill-red",
      "headline": "China Brokerages Said to Tighten Margin Lending Scrutiny to Curb Retail Losses Threatening Social Stability - finance.biggo.com",
      "date": "2026-08-10",
      "match": "curb",
      "count_7d": 1
    },
    "antitrust": {
      "triggered": true,
      "status": "触发复核",
      "pill": "pill-warn",
      "headline": "“Pay for Half” Offers a Better Remedy for Google’s Search Monopoly - promarket.org",
      "date": "2026-08-12",
      "match": "monopoly",
      "count_7d": 6
    },
    "power": {
      "triggered": true,
      "status": "触发复核",
      "pill": "pill-warn",
      "headline": "Texas Data Center Moratorium: Key Meeting Next Week; Watch These S&amp;P 500 Stocks - Investor's Business Daily",
      "date": "2026-08-14",
      "match": "moratorium",
      "count_7d": 28
    },
    "carry": {
      "triggered": true,
      "status": "触发复核",
      "pill": "pill-red",
      "headline": "BOJ’s First Rate Hike in 31 Years Gains Momentum, as Yen Carry Trade Unwind Fears Collide With Easing Oil Prices - economy.ac",
      "date": "2026-08-12",
      "match": "rate hike",
      "count_7d": 15
    },
    "debtwall": {
      "triggered": true,
      "status": "触发复核",
      "pill": "pill-warn",
      "headline": "CRE’s $65B Maturity Wall Is Finally Hitting - CRE Daily",
      "date": "2026-08-11",
      "match": "maturity wall",
      "count_7d": 4
    },
    "nbfi": {
      "triggered": false,
      "status": "监控中 · 近7日2条",
      "pill": "pill-green",
      "headline": "Has Bitcoin Price Bottomed? Institutional Traders Seem to Think So - CoinMarketCap",
      "date": "2026-08-14",
      "match": "",
      "count_7d": 2
    },
    "usdfunding": {
      "triggered": false,
      "status": "监控中 · 无近期新闻",
      "pill": "pill-green",
      "headline": "",
      "date": "",
      "match": "",
      "count_7d": 0
    },
    "cnflow": {
      "triggered": false,
      "status": "监控中 · 无近期新闻",
      "pill": "pill-green",
      "headline": "",
      "date": "",
      "match": "",
      "count_7d": 0
    }
  },
  "registry": [
    {
      "key": "nbfi",
      "name": "非银金融杠杆出清",
      "logic": "对冲基金/资管强平→火烧连营，局部压力变系统性踩踏",
      "trigger_desc": "强平/margin call/fire sale/basis平仓"
    },
    {
      "key": "usdfunding",
      "name": "美元融资 / 跨币种基差",
      "logic": "离岸美元荒→基差扩大→高杠杆头寸被迫平仓（08/20危机前兆）",
      "trigger_desc": "美元荒/基差扩大/repo紧张"
    },
    {
      "key": "cnflow",
      "name": "中国资金面 / 资本管制",
      "logic": "资本外流管制 或 房地产危机引发回流→AI相关中概/港股资金骤减",
      "trigger_desc": "外汇管制/QDII收紧/LGFV/地产违约/回流"
    }
  ],
  "fetch_failures": []
};
