// Auto-generated by fetch_soros_fred.py · DO NOT EDIT MANUALLY
// Last update: 2026-05-29 09:18 UTC
const FRED_DATA = {
  "updated_at": "2026-05-29 09:18 UTC",
  "flipped_count": 1,
  "flipped_total": 7,
  "signals": {
    "S1": {
      "current": "2.09%",
      "status": "观察",
      "pill": "pill-warn",
      "delta_30d": "+0.20% · 30D",
      "date": "2026-05-27"
    },
    "S2": {
      "current": "271bp",
      "status": "正常",
      "pill": "pill-green",
      "delta_30d": "-14bp · 30D",
      "date": "2026-05-27"
    },
    "AUX_BEI": {
      "current": "2.39%",
      "status": "正常",
      "pill": "pill-green",
      "delta_30d": "+0.00% · 30D",
      "date": "2026-05-28"
    },
    "AUX_DXY": {
      "current": "119.29",
      "status": "正常",
      "pill": "pill-green",
      "delta_30d": "+0.43 · 30D",
      "date": "2026-05-22"
    },
    "AUX_DGS10": {
      "current": "4.48%",
      "status": "正常",
      "pill": "pill-green",
      "delta_30d": "+0.22% · 30D",
      "date": "2026-05-27"
    },
    "AUX_VIX": {
      "current": "16.29",
      "status": "正常",
      "pill": "pill-green",
      "delta_30d": "-1.88 · 30D",
      "date": "2026-05-27"
    }
  },
  "weekly": {
    "gpu_prices": {
      "H100": {
        "min_hr": "$1.47/hr",
        "median_hr": "$2.94/hr",
        "max_hr": "$4.54/hr",
        "offers": 4,
        "date": "2026-05-29"
      },
      "H200": {
        "min_hr": "$3.82/hr",
        "median_hr": "$8.00/hr",
        "max_hr": "$35.16/hr",
        "offers": 14,
        "date": "2026-05-29"
      },
      "B200": {
        "min_hr": "$4.17/hr",
        "median_hr": "$18.47/hr",
        "max_hr": "$36.93/hr",
        "offers": 5,
        "date": "2026-05-29"
      }
    },
    "form4": {
      "NVDA": {
        "count_30d": 0,
        "latest_date": "N/A",
        "status": "正常",
        "pill": "pill-green"
      },
      "MSFT": {
        "count_30d": 1,
        "latest_date": "2026-05-18",
        "status": "正常",
        "pill": "pill-green"
      },
      "GOOGL": {
        "count_30d": 11,
        "latest_date": "2026-05-27",
        "status": "正常",
        "pill": "pill-green"
      },
      "META": {
        "count_30d": 26,
        "latest_date": "2026-05-28",
        "status": "异常密集",
        "pill": "pill-red"
      },
      "ORCL": {
        "count_30d": 1,
        "latest_date": "2026-05-07",
        "status": "正常",
        "pill": "pill-green"
      }
    }
  },
  "events": {
    "tips_daily": {
      "change_bp": -1.0,
      "triggered": false,
      "date": "2026-05-27",
      "level": "2.09%"
    }
  },
  "fetch_failures": []
};
