// Auto-generated by fetch_soros_fred.py · DO NOT EDIT MANUALLY
// Last update: 2026-06-10 00:15 UTC
const FRED_DATA = {
  "updated_at": "2026-06-10 00:15 UTC",
  "flipped_count": 1,
  "flipped_total": 7,
  "signals": {
    "S1": {
      "current": "2.21%",
      "status": "红色",
      "pill": "pill-red",
      "delta_30d": "+0.32% · 30D",
      "date": "2026-06-08"
    },
    "S2": {
      "current": "275bp",
      "status": "正常",
      "pill": "pill-green",
      "delta_30d": "-10bp · 30D",
      "date": "2026-06-08"
    },
    "AUX_BEI": {
      "current": "2.33%",
      "status": "正常",
      "pill": "pill-green",
      "delta_30d": "-0.11% · 30D",
      "date": "2026-06-09"
    },
    "AUX_DXY": {
      "current": "120.08",
      "status": "正常",
      "pill": "pill-green",
      "delta_30d": "+1.37 · 30D",
      "date": "2026-06-05"
    },
    "AUX_DGS10": {
      "current": "4.56%",
      "status": "正常",
      "pill": "pill-green",
      "delta_30d": "+0.25% · 30D",
      "date": "2026-06-08"
    },
    "AUX_VIX": {
      "current": "18.92",
      "status": "正常",
      "pill": "pill-green",
      "delta_30d": "+0.90 · 30D",
      "date": "2026-06-08"
    }
  },
  "weekly": {
    "gpu_prices": {
      "H100": {
        "min_hr": "$1.74/hr",
        "median_hr": "$2.19/hr",
        "max_hr": "$19.20/hr",
        "offers": 3,
        "date": "2026-06-10"
      },
      "H200": {
        "min_hr": "$1.52/hr",
        "median_hr": "$7.90/hr",
        "max_hr": "$28.43/hr",
        "offers": 9,
        "date": "2026-06-10"
      },
      "B200": {
        "min_hr": "$4.38/hr",
        "median_hr": "$10.38/hr",
        "max_hr": "$44.01/hr",
        "offers": 9,
        "date": "2026-06-10"
      }
    },
    "form4": {
      "NVDA": {
        "count_30d": 3,
        "latest_date": "2026-06-05",
        "status": "正常",
        "pill": "pill-green"
      },
      "MSFT": {
        "count_30d": 16,
        "latest_date": "2026-06-09",
        "status": "加速减持",
        "pill": "pill-warn"
      },
      "GOOGL": {
        "count_30d": 10,
        "latest_date": "2026-06-01",
        "status": "正常",
        "pill": "pill-green"
      },
      "META": {
        "count_30d": 26,
        "latest_date": "2026-06-03",
        "status": "异常密集",
        "pill": "pill-red"
      },
      "ORCL": {
        "count_30d": 8,
        "latest_date": "2026-06-02",
        "status": "正常",
        "pill": "pill-green"
      }
    }
  },
  "events": {
    "tips_daily": {
      "change_bp": 2.0,
      "triggered": false,
      "date": "2026-06-08",
      "level": "2.21%"
    },
    "capex": {
      "triggered": false,
      "status": "监控中 · 近7日15条",
      "pill": "pill-green",
      "headline": "Oracle (ORCL) Is Up 16.0% After AI Data Center Capex Becomes Focus Ahead of Earnings - Yahoo Finance",
      "date": "2026-06-05",
      "match": "",
      "count_7d": 15
    },
    "neocloud": {
      "triggered": true,
      "status": "触发复核",
      "pill": "pill-red",
      "headline": "Nebius: Please Don't Push It Off The Cliff (Rating Downgrade) (NASDAQ:NBIS) - Seeking Alpha",
      "date": "2026-06-09",
      "match": "downgrade",
      "count_7d": 11
    },
    "bond": {
      "triggered": false,
      "status": "监控中 · 近7日9条",
      "pill": "pill-green",
      "headline": "Amazon Seeks to Raise at Least C$7 Billion in Canada Bond Sale - Bloomberg.com",
      "date": "2026-06-08",
      "match": "",
      "count_7d": 9
    },
    "abs": {
      "triggered": false,
      "status": "监控中 · 无近期新闻",
      "pill": "pill-green",
      "headline": "",
      "date": "",
      "match": "",
      "count_7d": 0
    },
    "policy": {
      "triggered": false,
      "status": "监控中 · 近7日12条",
      "pill": "pill-green",
      "headline": "Taiwan Mulls Curbs on AI Chip Exports to China to Align With US - Bloomberg.com",
      "date": "2026-06-09",
      "match": "",
      "count_7d": 12
    },
    "leverage": {
      "triggered": true,
      "status": "触发复核",
      "pill": "pill-red",
      "headline": "South Korea unveils measures to stem won slide and curb speculation - Crypto Briefing",
      "date": "2026-06-08",
      "match": "curb",
      "count_7d": 3
    },
    "antitrust": {
      "triggered": true,
      "status": "触发复核",
      "pill": "pill-warn",
      "headline": "Microsoft Restores Some GitHub Repos, Keeps Others Offline as Miasma Probe Continues - The Hacker News",
      "date": "2026-06-09",
      "match": "probe",
      "count_7d": 6
    },
    "power": {
      "triggered": true,
      "status": "触发复核",
      "pill": "pill-warn",
      "headline": "City Council passes emergency data center moratorium and policy framework - Seattle City Council Blog (.gov)",
      "date": "2026-06-09",
      "match": "moratorium",
      "count_7d": 39
    },
    "carry": {
      "triggered": true,
      "status": "触发复核",
      "pill": "pill-red",
      "headline": "Can the Bank of Japan’s 1% rate hike spark another crypto selloff? - Bitget",
      "date": "2026-06-09",
      "match": "rate hike",
      "count_7d": 11
    },
    "debtwall": {
      "triggered": false,
      "status": "监控中 · 近7日1条",
      "pill": "pill-green",
      "headline": "Does Pinnacle West’s (PNW) Debt Refinance and EPS Outlook Change The Bull Case For The Stock? - Yahoo Finance",
      "date": "2026-06-06",
      "match": "",
      "count_7d": 1
    },
    "nbfi": {
      "triggered": false,
      "status": "监控中 · 无近期新闻",
      "pill": "pill-green",
      "headline": "",
      "date": "",
      "match": "",
      "count_7d": 0
    },
    "usdfunding": {
      "triggered": false,
      "status": "监控中 · 无近期新闻",
      "pill": "pill-green",
      "headline": "",
      "date": "",
      "match": "",
      "count_7d": 0
    },
    "cnflow": {
      "triggered": true,
      "status": "触发复核",
      "pill": "pill-warn",
      "headline": "China’s clampdown on capital flight wipes billions off UK banks - The Times",
      "date": "2026-06-04",
      "match": "flight",
      "count_7d": 9
    }
  },
  "registry": [
    {
      "key": "nbfi",
      "name": "非银金融杠杆出清",
      "logic": "对冲基金/资管强平→火烧连营，局部压力变系统性踩踏",
      "trigger_desc": "强平/margin call/fire sale/basis平仓"
    },
    {
      "key": "usdfunding",
      "name": "美元融资 / 跨币种基差",
      "logic": "离岸美元荒→基差扩大→高杠杆头寸被迫平仓（08/20危机前兆）",
      "trigger_desc": "美元荒/基差扩大/repo紧张"
    },
    {
      "key": "cnflow",
      "name": "中国资金面 / 资本管制",
      "logic": "资本外流管制 或 房地产危机引发回流→AI相关中概/港股资金骤减",
      "trigger_desc": "外汇管制/QDII收紧/LGFV/地产违约/回流"
    }
  ],
  "fetch_failures": []
};
